development:
  consumer_key: <%= ENV['EN_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['EN_CONSUMER_SECRET'] %>
  sandbox: false
production:
    consumer_key: <%= ENV['EN_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['EN_CONSUMER_SECRET'] %>
    sandbox: false
